commands:
  provision:
    begin: '/configure application-assurance group {partition} policy begin'
    charging-group: '/configure application-assurance group {partition} policy charging-group {charging_group} create'
    application: '/configure application-assurance group {partition} policy application {application} create'
    combine_app_cg: '/configure application-assurance group {partition} policy application "{application}"
    charging-group "{charging_group}"'
    app-group: '/configure application-assurance group {partition} policy app-group {application} create'
    combine_app_apg: '/configure application-assurance group {partition} policy application "{application}"
                         app-group "{application_group}"'
    default_cg: '/configure application-assurance group {partition} policy default-charging-group {charging_group}'
    commit: '/configure application-assurance group {partition} policy commit'
  rollback:
    begin: '/configure application-assurance group {partition} policy begin'
    application: '/configure application-assurance group {partition} policy no application {application}'
    charging-group: '/configure application-assurance group {partition} policy no charging-group {charging_group}'
    app-group: '/configure application-assurance group {partition} policy no app-group {application} create'
    commit: '/configure application-assurance group {partition} policy commit'